config/routes.rb
Rails.application.routes.draw do

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users, :controllers => { registrations: "registrations"}
  # devise_for :users
  root to: 'pages#home'
  get '/search_results', to: 'artists#search'
  get '/search_results/artist', to: 'artists#show'

  get '/artists/:artist_id/eventsearch', to: 'artists#eventsearch', as: 'eventsearch'
  get '/consumers/:consumer_id/event/:id', to: 'consumers_events#show', as: 'event_details'
  post '/artists/:artist_id/artist_request', to: 'artist_requests#create', as: 'create_artist_request'
  patch '/artists/:artist_id/artist_request/accept/:id', to: 'artist_requests#accept', as: 'accept_artist_request'
  patch '/artists/:artist_id/artist_request/decline/:id', to: 'artist_requests#decline', as: 'decline_artist_request'

  post '/artist/:artist_id/reserveday', to: 'artist#reserve_day', as: 'reserve_day'

    resources :consumers do
      resources :reviews, only: [:new, :edit, :update ,:destroy]
      resources :consumers_events
    end

    resources :artists do
      resources :reviews, only: [:create, :index ]
      resources :consumers_requests do
        resources :messages, only: [:create, :index, :new]
      end
    end


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/artist.rb
class Artist < ApplicationRecord
  # CATEGORY = [['Hair', 'hair'], ['Makeup', 'makeup'], ['Hair and Makeup', 'both']]
  belongs_to :user
  has_many :certifications
  has_many :artist_services
  has_many :artist_images
  has_many :messages, through: :consumer_requests
  has_many :reviews
  has_many :time_blocks

  geocoded_by :location
  after_validation :geocode, if: :location_changed?

  # validates :first_name, presence: true
  # validates :last_name, presence: true
  # validates :location, presence: true
  # validates :tags, presence: true
  mount_uploader :photo, PhotoUploader
end

app/controllers/artists_controller.rb
class ArtistsController < ApplicationController
  skip_before_action :authenticate_user!, only: [:search, :index, :show]
  before_action :set_artist, only: [:show, :edit, :update]

  def index
    @artists = Artist.all
  end

  def show
    @artist_gallery = ArtistImage.where(artist: @artist)
    @date = DateTime.now
    @review = Review.new
    @reviews = Review.where(artist_id: @artist)
    requests = ConsumerRequest.where(artist: @artist)
    @confirmed = requests.select { |request| request.status == 'confirmed' }
    @unconfirmed = requests.select { |request| request.status == 'unconfirmed' }
    unless TimeBlock.where(artist: @artist).empty?
      time_blocks = TimeBlock.where(artist: @artist)
      @time_blocks_by_date = time_blocks.group_by { |i| i.date.to_date}
    else
      @time_blocks_by_date = {}
    end
    @my_bids = ArtistRequest.where(artist: @artist)
  end

  def eventsearch
    @artist = Artist.find(params[:artist_id])
    @events = ConsumerEvent.all.reverse
    @request = ArtistRequest.new
    @coords = [@artist.latitude, @artist.longitude]

    #map

      @hash = Gmaps4rails.build_markers(@events) do |event, marker|
        if event.geocoded? && !event.date.past?
          marker.lat event.latitude
          marker.lng event.longitude
          marker.infowindow render_to_string(partial: "shared/map_box", locals: { event: event })
          marker.json({ :id => event.id })
        end
      end
  end

  def new
    @artist = Artist.new
    @artist_image = @artist.artist_images.build
  end

  def create
    @artist = Artist.new(artist_params)

    @artist.rating = 0.0
    @artist.user = current_user
    prices = [15, 43.50, 87, 33.10, 45, 60.99]
    params[:artist][:artist_services].each do |service|
      ArtistService.create({ name: service, price: prices.sample, artist: @artist})
    end

    if @artist.save
      if params[:artist_images]
        params[:artist_images]['image'].each do |i|
          @artist_image = @artist.artist_images.create!(:image => i)
       end
      end
      redirect_to artist_path(@artist)

    else
      render 'artists/new'
    end
  end

  def edit

  end

  def update

    prices = [50.0, 150.00, 100.00, 75.00, 80.00]

    if params[:artist][:artist_services]
      params[:artist][:artist_services].each do |service, price|
        ArtistService.where(artist: @artist).each do |service_to_destroy|
          service_to_destroy.destroy! if service == service_to_destroy.name
        end
        ArtistService.create({ name: service, price: prices.sample, artist: @artist})
      end
    end
    @artist.update(artist_params)

    if params[:artist_images]
      params[:artist_images]['image'].each do |i|
        @artist_image = @artist.artist_images.create!(:image => i)
      end
    end

    redirect_to artist_path(@artist)
  end

  def search

    service = params[:category]
    location = params[:location]
    long = params[:longitude]
    lat = params[:latitude]

    # consider adding a specific time to the search bar as we can now search by that
    # using ReturnAvailableArtists.new(params, artist).call
    begin
      time_range = MakeTimeRange.new(params[:date], params[:time]).call
    rescue
    end

    # by location and date and service (always filled in)
    if !location.empty? && !params[:date].empty?
      results_by_cat = service == "Choose service" ? Artist.all : Artist.where(category: service)
      results_by_cat_and_location = SearchArtistByLocation.new(results_by_cat, lat, long).call
      @results = results_by_cat_and_location.reject do |artist|
        CheckArtistClashesForSegment.new(artist, time_range).call
      end

    elsif !location.empty?

      results_by_cat = service == "Choose service" ? Artist.all : Artist.where(category: service)
      results_by_cat_and_location = SearchArtistByLocation.new(results_by_cat, lat, long).call
      @results = results_by_cat_and_location
      # raise

    # by date and service
    elsif !params[:date].empty?
      results_by_cat = service == "Choose service" ? Artist.all : Artist.where(category: service)
      @results = results_by_cat.reject do |artist|
        CheckArtistClashesForSegment.new(artist, time_range).call
      end

    # by service only
    else
      @results = service == "Choose service" ? Artist.all : Artist.where(category: service)
    end
  end

  def reserve_day

    # TimeBlock.new(date:, end_date:, artist:).save(:validate => false)
  end

  private
  def set_artist
    @artist = Artist.find(params[:id])
  end

  def artist_params
    params.require(:artist).permit(:first_name, :last_name, :bio, :location, :tags, :travel_range, :instagram_handle, :category, :photo, :photo_cache, {artist_service: []})
  end
end

# , artist_images_attributes: [:id, :artist_id, :image, :image_cache]

app/views/artists/edit.html.erb
<br>
<%= link_to 'Return to Dashboard', :back, class: 'btn-pamprd' %>
<%= render 'shared/artist-signup-edit'%>

app/views/artists/eventsearch.html.erb
<div class="event-search-container">
      <div class="event-search-results">
        <!-- insert search_event_card partial here -->
        <%= link_to artist_path(@artist) do %>
          <i class="fa fa-chevron-left" aria-hidden="true" style="color: 'white';"></i> Dashboard
        <% end %>
        <%= render 'shared/search_event_card' %>
      </div>

        <div class="event-search-map hidden-xs" id="searchmap">
            <%= render 'shared/searchmap' %>
        </div>

</div>

app/views/artists/index.html.erb
<%= render 'shared/search_filter_nav' %>
<% if user_signed_in? && current_user.is_consumer? %>
  <%#= link_to "Create your own event", new_consumer_consumers_event_path(current_user.consumer) %> <br>
<% end %>
<%#= link_to 'Return to search results', :back %>
<div class="search-container">

    <% @artists.each do |artist| %>
    <div class="search-result-card">
      <div class="row">
        <div class="col-xs-12 col-sm-4">
              <% if artist.photo %>
                <div class="search-img-wrapper">
                  <%= image_tag artist.photo %>
                </div>
              <% else %>
                <%= image_tag "http://www.breda.academy/wp-content/uploads/2016/11/best-facial-in-dubai-1.jpg", class: 'search-image', width: 300, height: 300, crop: :fill %>
              <% end %>

          </div>
    <!--       <img src=<%#= artist.photo  %> alt="kudoz" class="product-image hidden-xs"> -->
          <div class="col-xs-12 col-sm-4">
            <div class='search-body'>
              <%= link_to artist_path(artist) do %>
                <h3><%= artist.first_name %> <%=artist.last_name %></h3>
              <%end%>
              <ul class="list-inline profile-rating">
              <% if artist.rating && artist.rating > 0.0 %>
                <% artist.rating.round.times do %>
                  <li><i style="padding: 0;" class="fa fa-star"></i></li>
                <% end %>
              <% end %>
              </ul>
              <p> <%= artist.category.capitalize %> | <%= artist.location %></p>
              <p><%= artist.bio %></p>

            </div>
          </div>
          <div class="col-xs-12 col-sm-4">
            <div class="search-btn">
        <!--     <div class="product-contact"> -->
              <!-- <a href=""><i class="fa fa-heart"></i></a> -->
              <%= button_to "REQUEST", new_artist_consumers_request_path(artist.id),
              :class => "btn-pamprd", :method => :get %>
            </div>
          </div>
      </div>
    </div>
  <%end%>
</div>

app/views/artists/new.html.erb
<%= render 'shared/artist-signup'%>

app/views/artists/search.html.erb
<!-- <div class ="container"> -->
<%= render 'shared/search_banner' %>
<%= render 'shared/search_filter_nav.html.erb' %>
<%#= link_to 'View all artists', artists_path %>
<%= render 'shared/searchcard' %>
<!-- </div> -->

app/views/artists/show.html.erb
<% if user_signed_in? %>
  <% if current_user.is_artist? && current_user.artist == @artist %>
    <%= render 'shared/artist_private_profile' %>
  <% else %>
    <%= render 'shared/artist_public_profile' %>
  <% end %>
<% else %>
  <%= render 'shared/artist_public_profile' %>
<% end %>


<!-- <div class="profile-banner">
  <div class="banner-content">
    <img src="images/cam.jpeg" class="avatar">
    <h1><%= @artist.first_name %> <%= @artist.last_name %></h1>
     <ul class="list-inline profile-rating">
            <li><i class="fa fa-star"></i></li>
            <li><i class="fa fa-star"></i></li>
            <li><i class="fa fa-star"></i></li>
            <li><i class="fa fa-star"></i></li>
            <li><i class="fa fa-star"></i></li>
        </ul>
    <p><%= @artist.category %> | <%= @artist.location %> | <%= @artist.instagram_handle %></p>

  </div>
</div>
<div class="tabs">
  <a class="tab active" href="#">
    <h2>ABOUT</h2>
  </a>
  <a class="tab" href="#">
    <h2>PORTFOLIO</h2>
  </a>
  <a class="tab" href="#">
    <h2>REVIEWS</h2>
  </a>
  <a class="tab" href="#">
    <%#= button_to "REQUEST", new_artist_consumers_request_path(@artist.id),
    :class => "btn-pamprd", :method => :get %>
  </a>
</div>
<div class="container">
  <div class="row">
  <p><%= @artist.bio %></p>

  </div>

</div>
 -->