config/routes.rb
Rails.application.routes.draw do

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users, :controllers => { registrations: "registrations"}
  # devise_for :users
  root to: 'pages#home'
  get '/search_results', to: 'artists#search'
  get '/search_results/artist', to: 'artists#show'

  get '/artists/:artist_id/eventsearch', to: 'artists#eventsearch', as: 'eventsearch'
  get '/consumers/:consumer_id/event/:id', to: 'consumers_events#show', as: 'event_details'
  post '/artists/:artist_id/artist_request', to: 'artist_requests#create', as: 'create_artist_request'
  patch '/artists/:artist_id/artist_request/accept/:id', to: 'artist_requests#accept', as: 'accept_artist_request'
  patch '/artists/:artist_id/artist_request/decline/:id', to: 'artist_requests#decline', as: 'decline_artist_request'

  post '/artist/:artist_id/reserveday', to: 'artist#reserve_day', as: 'reserve_day'

    resources :consumers do
      resources :reviews, only: [:new, :edit, :update ,:destroy]
      resources :consumers_events
    end

    resources :artists do
      resources :reviews, only: [:create, :index ]
      resources :consumers_requests do
        resources :messages, only: [:create, :index, :new]
      end
    end


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/consumer.rb
class Consumer < ApplicationRecord
  belongs_to :user

  geocoded_by :address
  after_validation :geocode, if: :address_changed?

  # validates :name, presence: true
  # validates :city, presence: true
  # validates :phone_number, presence: true
  mount_uploader :profile_img, ProfileImgUploader
end

app/controllers/consumers_controller.rb
class ConsumersController < ApplicationController
  before_action :set_consumer, only: [:show, :destroy, :update, :edit]

  def index
    # all users - not necessary
    # @consumers = Consumer.all
  end

  def show
    @my_events = ConsumerEvent.where(user: current_user)
    @requests = ConsumerRequest.where(user_id: current_user.id)
    if @requests.any?
      @confirmed = @requests.select { |request| request.status == 'confirmed' && !request.is_past?}
      @pending = @requests.select { |request| request.status == 'unconfirmed'}
      @past = @requests.select {|request| request.status == 'confirmed' && request.is_past? }
    end
    # @artist_requests = ArtistRequest.where()
  end

  def new
    # new consumer object and render form
    @consumer = Consumer.new
  end

  def create
    # send form parameters
    # @consumers = Consumer.all
    @consumer = Consumer.new(consumer_params)
    if @consumer.save
      redirect_to consumer_path(@consumer)
    else
      render 'consumers/new'
    end
  end

  def destroy
    # delete your own profile
    @consumer.destroy!
  end

  def edit
    # supply form with existing consumer object
  end

  def update
    @consumer.update(consumer_params)
    redirect_to consumer_path(@consumer)
  end

  private
    # Use callbacks to share common setup or constraints between actions.
  def set_consumer

    @consumer = current_user.consumer

  end

  def consumer_params
    params.require(:consumer).permit(:first_name, :last_name, :address, :phone_number, :instagram, :profile_img, :profile_img_cache)
  end

  def prettify_dates(results_array)
    results_array.each do |result|
      result.date = result.date
    end
  end

end

app/views/consumers/edit.html.erb
<br>
<%= link_to 'Back', :back, class: 'back-btn' %>

<%= render 'shared/consumer-profile' %>

app/views/consumers/new.html.erb
<h1>Fill out your profile!</h1>
<%= render 'shared/consumer-profile' %>

app/views/consumers/show.html.erb
<div class="add-client-event-btn">
  <%= link_to new_consumer_consumers_event_path(current_user.consumer) do %>
    Add Event <i class="fa fa-plus fa-lg" aria-hidden="true"></i>
  <% end %>
</div>

<div class="client-profile-container">
  <div class="row">
    <div class="col-xs-12 col-sm-3">
      <div class="user-profile">
        <%= cl_image_tag @consumer.profile_img, width: 300, height: 300, crop: :fill, class: 'avatar-super-large' %>
        <p style="margin-top: 10px;">Name: <%= @consumer.first_name %> <%= @consumer.last_name %></p>
        <p>Address: <%= @consumer.address %></p>
        <p>Phone Number: <%= @consumer.phone_number %></p>
        <p>Instagram: @<%= @consumer.instagram %></p>

        <p><%= link_to 'Edit Profile', edit_consumer_path %></p>
         <%= link_to "Create Event", new_consumer_consumers_event_path(current_user.consumer), class: 'btn-pamprd' %>
      </div>
    </div>
  <div class="col-xs-12 col-sm-9">
    <div class="booking-container">


<!-- collapsible tabs -->
  <div class="panel-group" id="accordion" role="tablist" aria-multiselectable="true">
    <div class="panel panel-default">
      <div class="panel-heading" role="tab" id="headingFour">
        <h4 class="panel-title">
          <a role="button" data-toggle="collapse" data-parent="#accordion" href="#collapseFour" aria-expanded="true" aria-controls="collapseFour">
          Upcoming Bookings <i class="fa fa-caret-down" aria-hidden="true"></i>
          </a>
        </h4>
      </div>
      <div id="collapseFour" class="panel-collapse collapse in" role="tabpanel" aria-labelledby="headingThree">
        <div class="panel-body">
          <div class="row">
            <% if @confirmed.nil? %>
              <p>You do not have any upcoming bookings</p>
            <% else %>
              <%= render partial: 'shared/confirmed_booking_card' %>
            <% end %>
          </div>
        </div>
      </div>
    </div>
    <div class="panel panel-default">
      <div class="panel-heading" role="tab" id="headingThree">
        <h4 class="panel-title">
          <a class="collapsed" role="button" data-toggle="collapse" data-parent="#accordion" href="#collapseThree" aria-expanded="false" aria-controls="collapseThree">
          Your Events <i class="fa fa-caret-down" aria-hidden="true"></i>
          </a>
        </h4>
      </div>
      <div id="collapseThree" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingThree">
        <div class="panel-body">
          <div class="row">
            <% if @my_events.nil? %>
              <p>You have not created any events yet</p>
            <% else %>
              <%= render partial: 'shared/consumer_event_card' %>
            <% end %>
          </div>
        </div>
      </div>
    </div>
    <div class="panel panel-default">
      <div class="panel-heading" role="tab" id="headingOne">
        <h4 class="panel-title">
          <a role="button" data-toggle="collapse" data-parent="#accordion" href="#collapseOne" aria-expanded="false" aria-controls="collapseOne">
            Pending Bookings <i class="fa fa-caret-down" aria-hidden="true"></i>
          </a>
        </h4>
      </div>
      <div id="collapseOne" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingOne">
        <div class="panel-body">
          <div class="row">
            <% if @pending.nil? %>
              <p>You not not have any pending bookings</p>
            <% else %>
              <%= render partial: 'shared/unconfirmed_booking_card' %>
            <% end %>
          </div>
        </div>
      </div>
    </div>
    <div class="panel panel-default">
      <div class="panel-heading" role="tab" id="headingTwo">
        <h4 class="panel-title">
          <a class="collapsed" role="button" data-toggle="collapse" data-parent="#accordion" href="#collapseTwo" aria-expanded="false" aria-controls="collapseTwo">
          Past Bookings <i class="fa fa-caret-down" aria-hidden="true"></i>
          </a>
        </h4>
      </div>
      <div id="collapseTwo" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingTwo">
        <div class="panel-body">
          <div class="row">
            <% if @past.nil? %>
              <p>You not not have any recent bookings</p>
            <% else %>
              <%= render partial: 'shared/past_booking_card' %>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>













        </div>
      </div>
    </div>
  </div>