config/routes.rb
Rails.application.routes.draw do

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users, :controllers => { registrations: "registrations"}
  # devise_for :users
  root to: 'pages#home'
  get '/search_results', to: 'artists#search'
  get '/search_results/artist', to: 'artists#show'

  get '/artists/:artist_id/eventsearch', to: 'artists#eventsearch', as: 'eventsearch'
  get '/consumers/:consumer_id/event/:id', to: 'consumers_events#show', as: 'event_details'
  post '/artists/:artist_id/artist_request', to: 'artist_requests#create', as: 'create_artist_request'
  patch '/artists/:artist_id/artist_request/accept/:id', to: 'artist_requests#accept', as: 'accept_artist_request'
  patch '/artists/:artist_id/artist_request/decline/:id', to: 'artist_requests#decline', as: 'decline_artist_request'

  post '/artist/:artist_id/reserveday', to: 'artist#reserve_day', as: 'reserve_day'

    resources :consumers do
      resources :reviews, only: [:new, :edit, :update ,:destroy]
      resources :consumers_events
    end

    resources :artists do
      resources :reviews, only: [:create, :index ]
      resources :consumers_requests do
        resources :messages, only: [:create, :index, :new]
      end
    end


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/artist.rb
class Artist < ApplicationRecord
  # CATEGORY = [['Hair', 'hair'], ['Makeup', 'makeup'], ['Hair and Makeup', 'both']]
  belongs_to :user
  has_many :certifications
  has_many :artist_services
  has_many :artist_images
  has_many :messages, through: :consumer_requests
  has_many :reviews
  has_many :time_blocks

  geocoded_by :location
  after_validation :geocode, if: :location_changed?

  # validates :first_name, presence: true
  # validates :last_name, presence: true
  # validates :location, presence: true
  # validates :tags, presence: true
  mount_uploader :photo, PhotoUploader
end

app/models/artist_image.rb
class ArtistImage < ApplicationRecord
  belongs_to :artist

  mount_uploader :image, ImageUploader
end

app/models/artist_request.rb
class ArtistRequest < ApplicationRecord
  belongs_to :consumer_event
  belongs_to :artist
  validates :message, length: { minimum: 10 }
end

app/models/artist_service.rb
class ArtistService < ApplicationRecord
  belongs_to :artist

end

app/models/certification.rb
class Certification < ApplicationRecord
  belongs_to :artist
end

app/models/consumer.rb
class Consumer < ApplicationRecord
  belongs_to :user

  geocoded_by :address
  after_validation :geocode, if: :address_changed?

  # validates :name, presence: true
  # validates :city, presence: true
  # validates :phone_number, presence: true
  mount_uploader :profile_img, ProfileImgUploader
end

app/models/consumer_event.rb
class ConsumerEvent < ApplicationRecord
  belongs_to :user
  has_many :artist_requests

  geocoded_by :location
  # after_validation :geocode, if: :location_changed?
   after_validation :geocode

  # def confirmed?
  #   status == 'confirmed'
  # end

  # def generate_transaction
  #   if confirmed?
  #     Transaction.new(self.id)
  #   end
  # end

  def geocoded?
    self.latitude && self.longitude
  end

  def is_past?
    self.date < Time.now
  end

end

app/models/consumer_request.rb
class ConsumerRequest < ApplicationRecord
  belongs_to :artist
  has_many :messages, dependent: :destroy
  has_one :time_block, dependent: :destroy
  has_one :review, dependent: :destroy


  geocoded_by :address
  after_validation :geocode, if: :address_changed?

  # def confirmed?
  #   status == 'confirmed'
  # end

  # def generate_transaction
  #   if confirmed?
  #     Transaction.new(self.id)
  #   end
  # end

  def geocoded?
    self.latitude && self.longitude
  end

  def is_past?
    self.date < Time.now
  end

  def consumer
    Consumer.find_by(user_id: self.user_id)
  end

end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  belongs_to :consumer_request
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :artist
  belongs_to :user
  belongs_to :consumer_request
  validates :content, length: { minimum: 10 }
  after_save :auto_update_artist_rating

  private
  def auto_update_artist_rating
    counter = Review.where(artist_id: self.artist.id).count
    artist_reviews = Review.where(artist_id: self.artist.id).map {|review| review.rating.to_f}
    rating = (self.rating + artist_reviews.reduce { |memo, i| memo + i } )/((counter +1).to_f)
    self.artist.update(rating: rating)
  end
end

app/models/time_block.rb
class TimeBlock < ApplicationRecord
  belongs_to :artist
  belongs_to :consumer_request


  def duration
    ((self.end_date - self.date) * 24 * 60 * 60).to_i
  end

  def consumer_name
    if self.consumer_request
      self.consumer_request.consumer.first_name
    else
      'Day Blocked'
    end
  end

  def pretty_time
    self.date.strftime("%H %M")
  end

  def all_day?
    self.category == 'all day'
  end

  def consumer
    self.consumer_request.consumer
  end

end

app/models/transaction.rb
class Transaction < ApplicationRecord
  belongs_to :consumer_request
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  has_one :artist
  has_one :consumer
  has_many :reviews
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  def is_artist?
    self.artist != nil
  end

  def is_consumer?
    self.consumer != nil
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:home]
  def home

    @artists = Artist.all

    # if user_signed_in?
    #   @page_user = current_user
    # end

  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/calendar_helper.rb
module CalendarHelper
  def calendar(date = Date.today, block_times = nil, &block)
    Calendar.new(self, date, block_times, block).table
  end

  class Calendar < Struct.new(:view, :date, :block_times, :callback)
    HEADER = %w[Sunday Monday Tuesday Wednesday Thursday Friday Saturday]
    START_DAY = :Sunday

    delegate :content_tag, to: :view

    def table
      content_tag :table, class: "calendar table table-responsive table-bordered" do
        header + week_rows
      end
    end

    def header
      content_tag :tr do
        HEADER.map { |day| content_tag :th, day.first(3) }.join.html_safe
      end
    end

    def week_rows
      weeks.map do |week|
        content_tag :tr do
          week.map { |day| day_cell(day) }.join.html_safe
        end
      end.join.html_safe
    end

    def day_cell(day)
      content_tag :td, view.capture(day, &callback), class: day_classes(day)
    end

    def day_classes(day)
      block_times_for_day = block_times[day.to_date]
      classes = []
      if block_times_for_day
        classes << "hasblocks" if block_times_for_day
        classes << "reserved_day" if block_times_for_day.any? { |bt| bt.all_day? }
      end
      classes << "today" if day == Date.today
      classes << "notmonth" if day.month != date.month
      classes.empty? ? nil : classes.join(" ")
    end

    def weeks
      first = date.beginning_of_month.beginning_of_week
      last = date.end_of_month.end_of_week
      (first..last).to_a.in_groups_of(7)
    end


  end
end

app/helpers/meta_tags_helper.rb
# app/helpers/meta_tags_helper.rb

module MetaTagsHelper
  def meta_title
    content_for?(:meta_title) ? content_for(:meta_title) : DEFAULT_META["meta_title"]
  end

  def meta_description
    content_for?(:meta_description) ? content_for(:meta_description) : DEFAULT_META["meta_description"]
  end

  def meta_image
    meta_image = (content_for?(:meta_image) ? content_for(:meta_image) : DEFAULT_META["meta_image"])
    # little twist to make it work equally with an asset or a url
    meta_image.starts_with?("http") ? meta_image : image_url(meta_image)
  end
end

app/helpers/navbar_helper.rb
module NavbarHelper
  def transparent
     if controller_name == 'pages' && action_name == 'home'
      'transparent'
     else
      'black'
    end
  end
end

app/helpers/user_helper.rb
module UserHelper
  def display_name
     if current_user.is_artist?
      [@consumer_request.consumer.first_name, @consumer_request.consumer.last_name].join(' ')
     else
      [@consumer_request.artist.first_name, @consumer_request.artist.last_name].join(' ')
     end
  end

  def whos_message(m)
     m.user == current_user ? 'current_user' : 'other_user'
  end
end

app/views/shared/_artist_public_profile.html.erb
<div class="container">
<!--   <div class="profile-banner"> -->
    <div class="row">
      <div class="col-xs-12 col-sm-12">
        <div class="artist-banner-content">
          <% if @artist.photo %>
          <%= cl_image_tag @artist.photo, class: 'avatar-super-large', width: 300, height: 300, crop: :fill %>
          <% else %>
           <%= image_tag "http://www.breda.academy/wp-content/uploads/2016/11/best-facial-in-dubai-1.jpg", class: 'product-image hidden-xs', width: 300, height: 300, crop: :fill %>
          <% end %>
          <h1><%= @artist.first_name %> <%= @artist.last_name %></h1>
              <ul class="list-inline profile-rating">
              <% if @artist.rating > 0.0 %>
                <% @artist.rating.round.times do %>
                  <li><i style="padding: 0;" class="fa fa-star"></i></li>
                <% end %>
              <% else %>
                <% 5.times do %>
                  <li><i style="padding: 0;" class="fa fa-star-o"></i></li>
                <% end %>
              <% end %>
              </ul>
              <p class="number-of-reviews">(<%= @artist.reviews.size %>)</p>
          <p><%= @artist.try(:category).try(:capitalize) %> | <%= @artist.location %> | <a href="https://www.instagram.com/horvattamara" target="_blank"> <%= @artist.instagram_handle %></a>
          <%= button_to "REQUEST #{@artist.first_name.upcase}", new_artist_consumers_request_path(@artist.id),
          :class => "btn-pamprd request-btn", :method => :get %>

        </div>
      </div>
    </div>
<!--   </div> -->


<!-- Nav tabs -->
<!-- <div class="tab-container"> -->
  <div class="row">
    <div class="artist-profile-tabs">
      <ul class="nav nav-tabs" role="tablist">
          <li role="presentation" ><a href="#home" class="tab active" aria-controls="home" role="tab" data-toggle="tab" data-target="#about">About</a></li>
          <li role="presentation" ><a href="#profile" aria-controls="profile" role="tab" data-toggle="tab" data-target="#portfolio" class="tab">Portfolio</a></li>
          <li role="presentation"><a href="#messages"  class="tab" aria-controls="messages" role="tab" data-toggle="tab" data-target="#reviews">Reviews</a></li>
      </ul>

    </div>
  </div>
<!-- </div> -->

<!-- <div class="tab-container">
  <div class="row">
    <div class="tabs">
      <div class="col-xs-4 col-sm-4">
        <a class="tab active" href="#" data-target="#about">
          <h2>ABOUT</h2>
        </a>
      </div>
      <div class="col-xs-4 col-sm-4">
        <a class="tab" href="#" data-target="#portfolio">
          <h2>PORTFOLIO</h2>
        </a>
      </div>
      <div class="col-xs-4 col-sm-4">
        <a class="tab" href="#" data-target="#reviews">
          <h2>REVIEWS</h2>
        </a>
      </div>
    </div>
  </div>
</div> -->
<!-- <div class="profile-container"> -->
  <div class="tab-content" id="about">
    <div class="row">
      <div class="about-artist">
        <div class="col-xs-12 col-sm-7">
          <h2>About me</h2>
            <p><%= @artist.bio %></p>

            <h2>Forte</h2>
            <p><%= @artist.tags %></p>

            <h2>Toolbelt</h2>
            <p>Mac, Nars, etc...</p>
        </div>
        <div class="col-xs-12 col-sm-5">
          <%= render 'shared/artist_prices_card' %>
        </div>
      </div>
    </div>
  </div>
  <div class="tab-content hidden" id="portfolio">
    <div class="row">
      <% @artist_gallery.each do |i| %>

          <div class="col-xs-4 artist-portfolio-image">
            <%= link_to "#{i.image}", class: "swipebox" do %>
              <%= cl_image_tag i.image, width: 300, height: 300, crop: :fill, class: 'portfolio-img' %>
            <% end %>
          </div>
      <% end %>
    </div>
  </div>

  <div class="tab-content hidden" id="reviews">
  <% if @reviews.empty? %>
    <p class="text-center"><%= @artist.first_name %> currently doesn't have any reviews.</p>
    <% else %>
    <div id="reviews">
    <%= render 'reviews/review-card' %>
    </div>
    <% end %>
  </div>

<!-- </div> -->

</div>

app/views/shared/_consumer_booking_page.html.erb
<% if current_user.is_artist? %>
  <%= link_to artist_path(@artist) do %>
    <i class="fa fa-chevron-left" aria-hidden="true" style="color: 'white';"></i> Dashboard
  <% end %>
<% else %>
  <%= link_to consumer_path do %>
    <i class="fa fa-chevron-left" aria-hidden="true" style="color: 'white';"></i> Bookings
  <% end %>
<% end %>

<div class="booking-container">
  <div class="row">
    <div class="col-xs-12 col-sm-5">
      <div class="booking-card">
        <div class="booking-details">
          <div class="booking-artist">
          <!-- name and photo -->
          <% if current_user.is_artist? %>
          <!-- show consumer pic and name -->
            <%= cl_image_tag(@consumer_request.consumer.profile_img, class: "avatar-super-large") %>
            <h2><%= @consumer_request.consumer.first_name%> <%= @consumer_request.consumer.last_name %></h2>
          <% else %>
          <!-- show artist pic, name and info -->
            <%= link_to artist_path(@artist) do %>
             <%= cl_image_tag(@artist.photo, class: "avatar-super-large") %>
              <h2><%= @artist.first_name %> <%= @artist.last_name %></h2>
            <% end %>
              <ul class="list-inline profile-rating" style="display: inline; margin-top: 5px;">
              <% if @artist.rating > 0.0 %>
                <% @artist.rating.round.times do %>
                  <li><i style="padding: 0;" class="fa fa-star"></i></li>
                <% end %>
              <% else %>
                <% 5.times do %>
                  <li><i style="padding: 0;" class="fa fa-star-o"></i></li>
                <% end %>
              <% end %>
              </ul><p style="display: inline; font-style: italic;">(<%= @artist.reviews.size %>)</p>
          <% end %>
          </div>

          <div class="booking-info text-center">
            <p><%= @consumer_request.date.strftime('%b %d %Y at %I:%M%p') %></p>
            <p><%= @consumer_request.address %></p>

            <ul class="booking-services">
              <li style="font-weight: 600; font-size: 16px;"><%= @consumer_request.servicename %></li>
              <li style="font-size: 24px; color: #F7ABB2; font-weight: 700; margin-top: 10px; ">$<%= @consumer_request.final_price.to_i %></li>
            </ul>
          </div>

          <div class="booking-status">
          <% if current_user.is_artist? %>
            <!-- Accept Booking -->
            <% if @consumer_request.status == 'unconfirmed' %>
             <%= button_to "Accept", artist_consumers_request_path(current_user.artist, @consumer_request), data: {:confirm => 'Are you sure you want to accept this request?'},
            :class => "booking-status accept btn-pamprd", :method => :patch %>

            <!-- Decline Booking -->
            <nobr><%= button_to "Decline", artist_consumers_request_path(current_user.artist, @consumer_request), data: {:confirm => 'Are you sure you want to decline this request?'}, :class => "booking-status cancel-btn btn-pamprd", method: :delete %>

              <% else %>
              <!-- Cancel previously accepted booking -->
                <p class="confirmed">CONFIRMED</p>
                <p class="cancel-booking"><%= link_to "Cancel Booking", artist_consumers_request_path(@consumer_request),  data: {:confirm => 'Are you sure you want to cancel this booking?'},
            :class => "booking-status cancel", :method => :delete %></p>
              <% end %>


            <%else%>
              <% if @consumer_request.status == 'unconfirmed' %>
               <!--  <i class="fa fa-clock-o fa-4x" aria-hidden="true"></i> -->
                <p class="unconfirmed">UNCONFIRMED</p>
                <p class="cancel-booking"><%= link_to "Cancel Request", artist_consumers_request_path(@consumer_request.artist, @consumer_request), data: {:confirm => 'Are you sure you want to cancel this request?'}, :class => "booking-status cancel", method: :delete %></p>

              <% else %>
                <p class='confirmed'><%= @consumer_request.status %></p>
                <p class='cancel-booking'><%= link_to "Cancel Booking", artist_consumers_request_path(@consumer_request.artist, @consumer_request), data: {:confirm => 'Are you sure you want to cancel this booking?'}, :class => "booking-status cancel", method: :delete %></p>

              <% end %>
          <%end%>

          </div>
        </div>

        <div class="booking-location-map" id="map">
            <%= render 'shared/event_map' %>
           </div>


      </div>

    </div>
    <%#= render 'shared/event_map' %>
    <div class="col-xs-12 col-sm-7">

     <!--  <div class="messages-section"> -->
        <%= render 'shared/booking_messages' %>
   <!--    </div> -->

    </div>
  </div>
</div>

app/views/shared/_consumer_event_form.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-12 col-sm-6 col-sm-offset-2">
      <%# raise %>
      <div class="form" >
      <h1 class="form-title">Create your own event </h1>
      <%=  simple_form_for(@consumer_event, :url => consumer_consumers_events_path, :method => :post) do  |f| %>

      <%= f.text_field :date, placeholder: 'Date', required: true, class: 'consumer-request datepick request-time' %>
      <%= f.text_field :date, placeholder: 'Time', required: true, class: 'timepicker-default request-time', id: 'basicExample' %>
      <%= f.text_field :location, as: :string, label: "Where will this event take place?", placeholder: 'Address', required: true, class: 'request-address', id: 'flat_address' %>
      <%= f.input :description, placeholder: 'Describe your event', required: true, class: 'consumer-request', input_html: { minLength: 10, maxLength: 500 } %>
      <%= f.text_field :tags, placeholder: 'Give your event some tags', required: true, class: 'consumer-request' %>
      <%= f.input :budget, placeholder: 'Approximately how much would you like to spend on this event? ($)', required: true, class: 'consumer-request' %>
      <%= f.submit "Go!", class: 'btn-pamprd' %>
      <% end %>
      <p class="request-msg text-center">Check your dashboard for bids on this event from local artists and stylists!</p>
      </div>
    </div>
  </div>
</div>

app/views/shared/_navbar.html.erb
<nav class="navbar  navbar-fixed-top">
  <div class="navbar-wagon <%= transparent %>">
    <!-- Logo -->
    <div id='updo-logo'>
      <a href="/">
        <%= cl_image_tag("rsz_updo-logo-100_adj4ag.png", :width=>100, :height=>263, :crop=>"fit") %>
        <!-- <img src="https://maxcdn.icons8.com/Share/icon/Beauty//mirror1600.png" alt="logo"> -->
      </a>
    </div>

    <% if user_signed_in? %>
      <% if current_user.is_artist? %>
        <!-- Right Navigation -->
        <div class="navbar-wagon-right">

          <!-- Profile picture with dropdown list -->
          <div class="navbar-wagon-item">
            <div class="dropdown">
            <div class="navbar-wagon-right hidden-sm hidden-xs">
              <% if current_user.artist.photo %>
                <%= cl_image_tag current_user.artist.photo, class: 'avatar dropdown-toggle', id: 'navbar-wagon-menu', data: { toggle: 'dropdown' }, width: 300, height: 300, crop: :fill %><i class="fa fa-chevron-down " aria-hidden="true", data-toggle= 'dropdown'></i>
                <% else %>
                <%= cl_image_tag "http://res.cloudinary.com/dl12g2ws3/image/upload/v1505729708/profile-icon_xx3teu.png", class: 'avatar dropdown-toggle', id: 'navbar-wagon-menu', data: { toggle: 'dropdown' }, width: 300, height: 300, crop: :fill %><i class="fa fa-chevron-down" aria-hidden="true", data-toggle= 'dropdown'></i>
                <% end %>
                <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
                  <li><%= link_to 'Dashboard', artist_path(current_user.artist), class: "navbar-wagon-item navbar-wagon-link" %></li>
                  <li><%= link_to 'Log Out', destroy_user_session_path, method: :delete %></li>

                </ul>
             </div>
            </div>
            <div class="navbar-wagon-right hidden-md hidden-lg">
              <div class="dropdown">
              <i class="fa fa-bars dropdown-toggle text-white fa-2x" data-toggle="dropdown"></i>
              <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
                <li><%= link_to 'Dashboard', artist_path(current_user.artist), class: "navbar-wagon-item navbar-wagon-link" %></li>
                  <li><%= link_to 'Log Out', destroy_user_session_path, method: :delete %></li>
              </ul>
            </div>
           </div>



          </div>
        </div>
      <% elsif current_user.is_consumer? %>
        <div class="navbar-wagon-right">

          <!-- Profile picture with dropdown list -->
          <div class="navbar-wagon-item">
            <div class="dropdown">
              <div class="navbar-wagon-right hidden-sm hidden-xs">
            <% if current_user.consumer.profile_img %>
              <%= cl_image_tag current_user.consumer.profile_img, class: 'avatar dropdown-toggle', id: 'navbar-wagon-menu', data: { toggle: 'dropdown' }, width: 300, height: 300, crop: :fill %><i class="fa fa-chevron-down" aria-hidden="true", data-toggle= 'dropdown'></i>
                <% else %>
              <%= cl_image_tag "http://res.cloudinary.com/dl12g2ws3/image/upload/v1505729708/profile-icon_xx3teu.png", class: 'avatar dropdown-toggle', id: 'navbar-wagon-menu', data: { toggle: 'dropdown' }, width: 300, height: 300, crop: :fill %><i class="fa fa-chevron-down" aria-hidden="true", data-toggle= 'dropdown'></i>
              <% end %>
              <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
                <li><%= link_to 'Dashboard', consumer_path(current_user), class: "navbar-wagon-item navbar-wagon-link" %></li>
                <li><%= link_to 'Log Out', destroy_user_session_path, method: :delete %></li>
              </ul>
              </div>
            </div>
            <div class="navbar-wagon-right hidden-md hidden-lg">
              <div class="dropdown">
              <i class="fa fa-bars dropdown-toggle text-white fa-2x" data-toggle="dropdown"></i>
              <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
                <li><%= link_to 'Dashboard', consumer_path(current_user), class: "navbar-wagon-item navbar-wagon-link" %></li>
                <li><%= link_to 'Log Out', destroy_user_session_path, method: :delete %></li>
              </ul>
            </div>
          </div>
        </div>
      <% end %>
    <% else %>

      <div class="navbar-wagon-right hidden-sm hidden-xs">
        <div id="sign-up-btn">
          <%= button_to 'Sign Up', new_user_registration_path, :method => :get, class: "btn-pamprd" %>
        </div>
        <%= link_to 'LOGIN', new_user_session_path, class: "navbar-wagon-item navbar-wagon-link text-white" %>
      </div>

      <div class="navbar-wagon-right hidden-md hidden-lg">
        <div class="dropdown">
        <i class="fa fa-bars dropdown-toggle text-white fa-2x" data-toggle="dropdown"></i>
        <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
          <li><%= link_to 'Sign Up', new_user_registration_path, class: "navbar-wagon-item navbar-wagon-link" %></li>
          <li><%= link_to 'Login', new_user_session_path, class: "navbar-wagon-item navbar-wagon-link" %></li>
        </ul>
      </div>
     </div>
    <% end %>
  </div>
</nav>

app/views/shared/_searchcard.html.erb
<% if @results.empty? %>
  <p class="text-center">No results.</p>
  <p class="text-center"> <%= link_to "Search Again", root_path %></p>
  <% if user_signed_in? && current_user.is_consumer? %>
  <%#= link_to "Create your own event", new_consumer_consumers_event_path(current_user.consumer) %>
  <% end %>
<% end %>

<div class="search-container">
  <% if user_signed_in? && current_user.is_consumer? %>
    <%#= link_to "Create your own event", new_consumer_consumers_event_path(current_user.consumer) %>
  <% end %>
    <% @results.each do |artist| %>
    <div class="search-result-card">
      <div class="row">
        <div class="col-xs-12 col-sm-3">
              <% if artist.photo %>
                <div class="search-img-wrapper">
                  <%= cl_image_tag artist.photo, class: 'avatar-square-search' %>
                </div>
              <% else %>
                <%= image_tag "search-placeholder_ainljs.jpg", class: 'search-image', width: 300, height: 300, crop: :fill %>
              <% end %>

          </div>
    <!--       <img src=<%#= artist.photo  %> alt="kudoz" class="product-image hidden-xs"> -->
          <div class="col-xs-12 col-sm-6">
            <div class='search-body'>
              <%= link_to artist_path(artist) do %>
                <h3><%= artist.first_name %> <%=artist.last_name %></h3>
              <%end%>
              <ul class="list-inline profile-rating", style="display: inline;">
              <% if artist.rating && artist.rating > 0.0 %>
                <% artist.rating.round.times do %>
                  <li><i style="padding: 0;" class="fa fa-star"></i></li>
                <% end %>
              <% else %>
                <% 5.times do %>
                  <li><i style="padding: 0;" class="fa fa-star-o"></i></li>
                <% end %>
              <% end %>
              </ul>
              <p style="font-style: italic; display: inline;">(<%= artist.reviews.size %>)</p>
              <p class="paragraph-bold"> <%= artist.try(:category).try(:capitalize)%> | <%= artist.location %></p>
              <p style="font-style: italic"><%= artist.tags %></p>
              <% if artist.bio %>
              <p><%= artist.bio.first(200) %>...</p>
              <% end %>

            </div>
          </div>
          <div class="col-xs-12 col-sm-3">
            <div class="search-btn">
        <!--     <div class="product-contact"> -->
              <!-- <a href=""><i class="fa fa-heart"></i></a> -->
              <%= button_to "REQUEST", new_artist_consumers_request_path(artist.id),
              :class => "btn-pamprd", :method => :get %>
            </div>
          </div>
      </div>
    </div>
  <%end%>
</div>

app/views/shared/_unconfirmed_booking_card.html.erb
    <% @pending.sort_by(&:date).each do |booking| %>

    <div class="col-xs-12 col-sm-4">
        <div class="booking-card">
          <div class="booking-bkgrd-image card__image--flowers"></div>
            <div class="booking-user-image">
            <%= cl_image_tag booking.artist.photo, class: 'booking-card-user', width: 300, height: 300, crop: :fill %>
             <!-- <img class="booking-card-user" src="https://kitt.lewagon.com/placeholder/users/tgenaitay"> -->
            </div>
            <div class="booking-card-content">
              <div class="booking-name">
              <%= link_to artist_path(booking.artist.id) do %>
                <p><%=booking.artist.first_name%> <%=booking.artist.last_name%></p>
                <% end %>
              </div>

                <p class="card__text"><%=booking.address%> | <%=booking.date.strftime('%b %d %Y, %I:%M%p')%></p>
                <p class="card__text"><%=booking.servicename%> - $<%=booking.final_price %></p>
                <p class="booking-status"><%=booking.status%></p>
                <!-- <button class="btn-pamprd">View Booking</button> -->
                <%= button_to "View Booking", artist_consumers_request_path(booking.artist, booking), :class => "btn-pamprd", :method => :get %>
            </div>
          </div>
      </div>
    <% end %>