config/routes.rb
Rails.application.routes.draw do

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users, :controllers => { registrations: "registrations"}
  # devise_for :users
  root to: 'pages#home'
  get '/search_results', to: 'artists#search'
  get '/search_results/artist', to: 'artists#show'

  get '/artists/:artist_id/eventsearch', to: 'artists#eventsearch', as: 'eventsearch'
  get '/consumers/:consumer_id/event/:id', to: 'consumers_events#show', as: 'event_details'
  post '/artists/:artist_id/artist_request', to: 'artist_requests#create', as: 'create_artist_request'
  patch '/artists/:artist_id/artist_request/accept/:id', to: 'artist_requests#accept', as: 'accept_artist_request'
  patch '/artists/:artist_id/artist_request/decline/:id', to: 'artist_requests#decline', as: 'decline_artist_request'

  post '/artist/:artist_id/reserveday', to: 'artist#reserve_day', as: 'reserve_day'

    resources :consumers do
      resources :reviews, only: [:new, :edit, :update ,:destroy]
      resources :consumers_events
    end

    resources :artists do
      resources :reviews, only: [:create, :index ]
      resources :consumers_requests do
        resources :messages, only: [:create, :index, :new]
      end
    end


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/artist.rb
class Artist < ApplicationRecord
  # CATEGORY = [['Hair', 'hair'], ['Makeup', 'makeup'], ['Hair and Makeup', 'both']]
  belongs_to :user
  has_many :certifications
  has_many :artist_services
  has_many :artist_images
  has_many :messages, through: :consumer_requests
  has_many :reviews
  has_many :time_blocks

  geocoded_by :location
  after_validation :geocode, if: :location_changed?

  # validates :first_name, presence: true
  # validates :last_name, presence: true
  # validates :location, presence: true
  # validates :tags, presence: true
  mount_uploader :photo, PhotoUploader
end

app/controllers/artists_controller.rb
class ArtistsController < ApplicationController
  skip_before_action :authenticate_user!, only: [:search, :index, :show]
  before_action :set_artist, only: [:show, :edit, :update]

  def index
    @artists = Artist.all
  end

  def show
    @artist_gallery = ArtistImage.where(artist: @artist)
    @date = DateTime.now
    @review = Review.new
    @reviews = Review.where(artist_id: @artist)
    requests = ConsumerRequest.where(artist: @artist)
    @confirmed = requests.select { |request| request.status == 'confirmed' }
    @unconfirmed = requests.select { |request| request.status == 'unconfirmed' }
    unless TimeBlock.where(artist: @artist).empty?
      time_blocks = TimeBlock.where(artist: @artist)
      @time_blocks_by_date = time_blocks.group_by { |i| i.date.to_date}
    else
      @time_blocks_by_date = {}
    end
    @my_bids = ArtistRequest.where(artist: @artist)
  end

  def eventsearch
    @artist = Artist.find(params[:artist_id])
    @events = ConsumerEvent.all.reverse
    @request = ArtistRequest.new
    @coords = [@artist.latitude, @artist.longitude]

    #map

      @hash = Gmaps4rails.build_markers(@events) do |event, marker|
        if event.geocoded? && !event.date.past?
          marker.lat event.latitude
          marker.lng event.longitude
          marker.infowindow render_to_string(partial: "shared/map_box", locals: { event: event })
          marker.json({ :id => event.id })
        end
      end
  end

  def new
    @artist = Artist.new
    @artist_image = @artist.artist_images.build
  end

  def create
    @artist = Artist.new(artist_params)

    @artist.rating = 0.0
    @artist.user = current_user
    prices = [15, 43.50, 87, 33.10, 45, 60.99]
    params[:artist][:artist_services].each do |service|
      ArtistService.create({ name: service, price: prices.sample, artist: @artist})
    end

    if @artist.save
      if params[:artist_images]
        params[:artist_images]['image'].each do |i|
          @artist_image = @artist.artist_images.create!(:image => i)
       end
      end
      redirect_to artist_path(@artist)

    else
      render 'artists/new'
    end
  end

  def edit

  end

  def update

    prices = [50.0, 150.00, 100.00, 75.00, 80.00]

    if params[:artist][:artist_services]
      params[:artist][:artist_services].each do |service, price|
        ArtistService.where(artist: @artist).each do |service_to_destroy|
          service_to_destroy.destroy! if service == service_to_destroy.name
        end
        ArtistService.create({ name: service, price: prices.sample, artist: @artist})
      end
    end
    @artist.update(artist_params)

    if params[:artist_images]
      params[:artist_images]['image'].each do |i|
        @artist_image = @artist.artist_images.create!(:image => i)
      end
    end

    redirect_to artist_path(@artist)
  end

  def search

    service = params[:category]
    location = params[:location]
    long = params[:longitude]
    lat = params[:latitude]

    # consider adding a specific time to the search bar as we can now search by that
    # using ReturnAvailableArtists.new(params, artist).call
    begin
      time_range = MakeTimeRange.new(params[:date], params[:time]).call
    rescue
    end

    # by location and date and service (always filled in)
    if !location.empty? && !params[:date].empty?
      results_by_cat = service == "Choose service" ? Artist.all : Artist.where(category: service)
      results_by_cat_and_location = SearchArtistByLocation.new(results_by_cat, lat, long).call
      @results = results_by_cat_and_location.reject do |artist|
        CheckArtistClashesForSegment.new(artist, time_range).call
      end

    elsif !location.empty?

      results_by_cat = service == "Choose service" ? Artist.all : Artist.where(category: service)
      results_by_cat_and_location = SearchArtistByLocation.new(results_by_cat, lat, long).call
      @results = results_by_cat_and_location
      # raise

    # by date and service
    elsif !params[:date].empty?
      results_by_cat = service == "Choose service" ? Artist.all : Artist.where(category: service)
      @results = results_by_cat.reject do |artist|
        CheckArtistClashesForSegment.new(artist, time_range).call
      end

    # by service only
    else
      @results = service == "Choose service" ? Artist.all : Artist.where(category: service)
    end
  end

  def reserve_day

    # TimeBlock.new(date:, end_date:, artist:).save(:validate => false)
  end

  private
  def set_artist
    @artist = Artist.find(params[:id])
  end

  def artist_params
    params.require(:artist).permit(:first_name, :last_name, :bio, :location, :tags, :travel_range, :instagram_handle, :category, :photo, :photo_cache, {artist_service: []})
  end
end

# , artist_images_attributes: [:id, :artist_id, :image, :image_cache]

app/views/artists/dashboard/_artist_bookings.html.erb
<div class="row">
  <div class="col-xs-12 col-md-6">
    <div class="row">
      <div class="col-xs-12">
        <div class="artist-profile dash-bookings">
          <div class="row">
            <div class="col-xs-12 col-md-4">
              <%#= image_tag @artist.photo, class: 'profile-pic', width: 300, height: 300, crop: :fill %>
               <% if @artist.photo %>
              <%= image_tag @artist.photo, class: 'avatar-xlarge', width: 300, height: 300, crop: :fill %>
              <% else %>
              <%= image_tag "http://www.breda.academy/wp-content/uploads/2016/11/best-facial-in-dubai-1.jpg", class: 'artist-profile-pic', width: 300, height: 300, crop: :fill %>
              <% end %>

            </div>
            <div class="col-xs-12 col-md-8">
              <ul class="artist-profile-info">
                <li><p class="artist-name"><%= @artist.first_name %> <%= @artist.last_name %></p></li>
                <li><p class="artist-location"><%= @artist.location %></p></li>
                <li>@<%= @artist.instagram_handle %>  <%= @artist.category %></li>
                <li><%= @artist.bio.first(300) %>...</li>
                <li><p class="artist-tags"><%= @artist.tags %></p></li>
              </ul>
            </div>
          </div>
        </div>
        <div class="row">
          <div class="col-xs-12 ">
            <%= render partial: 'shared/bid_card' %>
          </div>
        </div>



    </div>
  </div>
  </div>

  <div class="col-xs-12 col-md-6">
    <div class="new-requests dash-bookings">
      <h2>New Requests</h2>
        <% if @unconfirmed.empty? %>
          <p>You don't have any new requests!</p>
        <% else %>
          <%= render partial: 'shared/unconfirmed_booking_listing' %>
        <% end %>
    </div>

    <div class="upcoming-bookings dash-bookings">
      <h2>Upcoming Bookings</h2>
        <% if @confirmed.empty? %>
          <p>You don't have any confirmed bookings!</p>
        <% else %>
          <%= render partial: 'shared/confirmed_booking_listing' %>
        <% end %>
    </div>
  </div>

</div>

app/views/artists/dashboard/_artist_calendar.html.erb
            <div class="artist-calendar">
                      <div id="bookings">
          <!-- <#% raise %> -->
                <%#= link_to "<", date: @date.prev_month %>
                <h2 id='month'><%= @date.strftime("%B %Y") %></h2>
                <%#= link_to ">", date: @date.next_month %>

                <%= calendar(@date, @time_blocks_by_date)  do |date| %>
                  <%= date.day %>
                  <% if @time_blocks_by_date %>
                  <% if @time_blocks_by_date[date.to_date] %>
                  <ul>
                    <% @time_blocks_by_date[date.to_date].each do |timeblock| %>
                    <%# raise %>
                      <li><%= timeblock.pretty_time %> - <%= link_to timeblock.consumer_name, consumer_consumers_events_path(timeblock.consumer, timeblock.consumer_request)  %>

                      </li>
                      <%#= button_to "Block Day", reserve_day_path(date), :class => "btn-pamprd", :method => :get %>

                      <% end %>
                  </ul>
                  <% end %>

                <% end %>
                <% end %>
              </div>

app/views/artists/dashboard/_artist_dashboard_nav.html.erb
  <ul class="artist-dashboard-nav">
      <li>
        <a href="#bookings" class="dash-tab" aria-controls="home" role="tab" data-toggle="tab" data-target="#bookings"><i class="fa fa-calendar-check-o  fa-2x" aria-hidden="true"></i><p class="dash-nav-header">Bookings</p></a>
      </li>
      <li>
        <a href="#calendar" class="dash-tab" aria-controls="home" role="tab" data-toggle="tab" data-target="#calendar"><i class="fa fa-calendar fa-2x" aria-hidden="true"></i><p class="dash-nav-header">Calendar</p></a>
      </li>

      <li>
        <a href="#financials" class="dash-tab" aria-controls="home" role="tab" data-toggle="tab" data-target="#financials"><i class="fa fa-usd fa-2x" aria-hidden="true"></i><p class="dash-nav-header">Financials</p></a>
      </li>

      <li>
        <%= link_to edit_artist_path(@artist.id), class: 'dash-tab' do %>
          <i class="fa fa-pencil fa-2x" aria-hidden="true"></i><p class="dash-nav-header">Edit Profile</p>
        <% end %>
      </li>

      <li>
        <a href="#settings" class="dash-tab" aria-controls="home" role="tab" data-toggle="tab" data-target="#settings"><i class="fa fa-cog fa-2x" aria-hidden="true"></i><p class="dash-nav-header">Settings</p></a>
      </li>

  </ul>

app/views/artists/dashboard/_artist_financials.html.erb
<div class="artist-financials">
  <h2>Coming Soon</h2>
</div>